//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int StateId { get; set; }
        public System.DateTime Date { get; set; }
        public long priority { get; set; }
        public string TaskTitle { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual State State { get; set; }
    }
}
